name: Ruff Code Quality

on:
  push:
    branches: [ main ]
    paths:
        - '**.py'
        - 'ruff.toml'

  # Will check PRs on main for code-quality issues
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
        - '**.py'
        - 'ruff.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Currently pinning (could use requirements.txt or pyproject.toml)
      - name: Install Ruff
        run: pip install ruff==0.12.0

      - name: Run ruff format check
        run: ruff format --check .

      - name: Run ruff lint check
        run: ruff check .